// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budgets.sql

package store

import (
	"context"
)

const deleteBudgetAt = `-- name: DeleteBudgetAt :exec
DELETE FROM budgets WHERE category_id IS ?1 AND effective_from = ?2
`

type DeleteBudgetAtParams struct {
	CategoryID    *int64
	EffectiveFrom string
}

func (q *Queries) DeleteBudgetAt(ctx context.Context, arg DeleteBudgetAtParams) error {
	_, err := q.db.ExecContext(ctx, deleteBudgetAt, arg.CategoryID, arg.EffectiveFrom)
	return err
}

const insertBudget = `-- name: InsertBudget :exec
INSERT INTO budgets (category_id, effective_from, amount_cents) VALUES (?, ?, ?)
`

type InsertBudgetParams struct {
	CategoryID    *int64
	EffectiveFrom string
	AmountCents   *int64
}

func (q *Queries) InsertBudget(ctx context.Context, arg InsertBudgetParams) error {
	_, err := q.db.ExecContext(ctx, insertBudget, arg.CategoryID, arg.EffectiveFrom, arg.AmountCents)
	return err
}

const listBudgetsUpTo = `-- name: ListBudgetsUpTo :many
SELECT id, category_id, effective_from, amount_cents, created_at FROM budgets WHERE effective_from <= ? ORDER BY effective_from, id
`

// All budget rows effective on or before the month, oldest first; the last row
// per category is the effective one.
func (q *Queries) ListBudgetsUpTo(ctx context.Context, effectiveFrom string) ([]Budget, error) {
	rows, err := q.db.QueryContext(ctx, listBudgetsUpTo, effectiveFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Budget{}
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.EffectiveFrom,
			&i.AmountCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopExpenseCategories = `-- name: ListTopExpenseCategories :many
SELECT id, parent_id, type, name, icon, color, archived, created_at FROM categories WHERE type = 'expense' AND parent_id IS NULL ORDER BY id
`

func (q *Queries) ListTopExpenseCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listTopExpenseCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Type,
			&i.Name,
			&i.Icon,
			&i.Color,
			&i.Archived,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const monthExpenseByTopCategory = `-- name: MonthExpenseByTopCategory :many
SELECT cast(coalesce(c.parent_id, c.id) AS INTEGER)                                       AS top_category_id,
       cast(sum(e.amount_cents) AS INTEGER)                                               AS spent_cents,
       cast(sum(CASE WHEN e.status = 'pending' THEN e.amount_cents ELSE 0 END) AS INTEGER) AS pending_cents
FROM entries e
         JOIN categories c ON c.id = e.category_id
WHERE e.type = 'expense'
  AND e.date >= ?1
  AND e.date <= ?2
GROUP BY coalesce(c.parent_id, c.id)
`

type MonthExpenseByTopCategoryParams struct {
	FromDate string
	ToDate   string
}

type MonthExpenseByTopCategoryRow struct {
	TopCategoryID int64
	SpentCents    int64
	PendingCents  int64
}

func (q *Queries) MonthExpenseByTopCategory(ctx context.Context, arg MonthExpenseByTopCategoryParams) ([]MonthExpenseByTopCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, monthExpenseByTopCategory, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonthExpenseByTopCategoryRow{}
	for rows.Next() {
		var i MonthExpenseByTopCategoryRow
		if err := rows.Scan(&i.TopCategoryID, &i.SpentCents, &i.PendingCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
