// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package store

import (
	"context"
)

const archiveChildCategories = `-- name: ArchiveChildCategories :exec
UPDATE categories SET archived = TRUE WHERE parent_id = ?
`

func (q *Queries) ArchiveChildCategories(ctx context.Context, parentID *int64) error {
	_, err := q.db.ExecContext(ctx, archiveChildCategories, parentID)
	return err
}

const countCategoryReferences = `-- name: CountCategoryReferences :one
SELECT (SELECT count(*) FROM entries e WHERE e.category_id = ?1)    AS entries,
       (SELECT count(*) FROM templates t WHERE t.category_id = ?1)  AS templates,
       (SELECT count(*) FROM budgets b WHERE b.category_id = ?1)    AS budgets,
       (SELECT count(*) FROM categories ch WHERE ch.parent_id = ?1) AS children
`

type CountCategoryReferencesRow struct {
	Entries   int64
	Templates int64
	Budgets   int64
	Children  int64
}

func (q *Queries) CountCategoryReferences(ctx context.Context, id int64) (CountCategoryReferencesRow, error) {
	row := q.db.QueryRowContext(ctx, countCategoryReferences, id)
	var i CountCategoryReferencesRow
	err := row.Scan(
		&i.Entries,
		&i.Templates,
		&i.Budgets,
		&i.Children,
	)
	return i, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (parent_id, type, name, icon, color, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateCategoryParams struct {
	ParentID  *int64
	Type      string
	Name      string
	Icon      string
	Color     string
	CreatedAt string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createCategory,
		arg.ParentID,
		arg.Type,
		arg.Name,
		arg.Icon,
		arg.Color,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = ?
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, parent_id, type, name, icon, color, archived, created_at FROM categories WHERE id = ?
`

func (q *Queries) GetCategory(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Type,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const getCategoryWithCounts = `-- name: GetCategoryWithCounts :one
SELECT c.id, c.parent_id, c.type, c.name, c.icon, c.color, c.archived,
       (SELECT count(*)
        FROM entries e
                 JOIN categories ec ON ec.id = e.category_id
        WHERE (ec.id = c.id OR ec.parent_id = c.id)
          AND e.date >= ?1
          AND e.date <= ?2)                           AS usage_count,
       (SELECT count(*) FROM entries e WHERE e.category_id = c.id) AS entry_count
FROM categories c
WHERE c.id = ?3
`

type GetCategoryWithCountsParams struct {
	Since string
	Until string
	ID    int64
}

type GetCategoryWithCountsRow struct {
	ID         int64
	ParentID   *int64
	Type       string
	Name       string
	Icon       string
	Color      string
	Archived   bool
	UsageCount int64
	EntryCount int64
}

func (q *Queries) GetCategoryWithCounts(ctx context.Context, arg GetCategoryWithCountsParams) (GetCategoryWithCountsRow, error) {
	row := q.db.QueryRowContext(ctx, getCategoryWithCounts, arg.Since, arg.Until, arg.ID)
	var i GetCategoryWithCountsRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Type,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.Archived,
		&i.UsageCount,
		&i.EntryCount,
	)
	return i, err
}

const listCategoriesWithCounts = `-- name: ListCategoriesWithCounts :many
SELECT c.id, c.parent_id, c.type, c.name, c.icon, c.color, c.archived,
       (SELECT count(*)
        FROM entries e
                 JOIN categories ec ON ec.id = e.category_id
        WHERE (ec.id = c.id OR ec.parent_id = c.id)
          AND e.date >= ?1
          AND e.date <= ?2)                           AS usage_count,
       (SELECT count(*) FROM entries e WHERE e.category_id = c.id) AS entry_count
FROM categories c
ORDER BY usage_count DESC, c.name COLLATE NOCASE, c.id
`

type ListCategoriesWithCountsParams struct {
	Since string
	Until string
}

type ListCategoriesWithCountsRow struct {
	ID         int64
	ParentID   *int64
	Type       string
	Name       string
	Icon       string
	Color      string
	Archived   bool
	UsageCount int64
	EntryCount int64
}

// usage_count: entries dated in [since, until]; for a top-level category this
// includes its children. entry_count: all-time entries on this category only.
func (q *Queries) ListCategoriesWithCounts(ctx context.Context, arg ListCategoriesWithCountsParams) ([]ListCategoriesWithCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesWithCounts, arg.Since, arg.Until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesWithCountsRow{}
	for rows.Next() {
		var i ListCategoriesWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Type,
			&i.Name,
			&i.Icon,
			&i.Color,
			&i.Archived,
			&i.UsageCount,
			&i.EntryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopLevelColors = `-- name: ListTopLevelColors :many
SELECT color FROM categories WHERE type = ? AND parent_id IS NULL
`

func (q *Queries) ListTopLevelColors(ctx context.Context, type_ string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTopLevelColors, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var color string
		if err := rows.Scan(&color); err != nil {
			return nil, err
		}
		items = append(items, color)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCategoryArchived = `-- name: SetCategoryArchived :exec
UPDATE categories SET archived = ? WHERE id = ?
`

type SetCategoryArchivedParams struct {
	Archived bool
	ID       int64
}

func (q *Queries) SetCategoryArchived(ctx context.Context, arg SetCategoryArchivedParams) error {
	_, err := q.db.ExecContext(ctx, setCategoryArchived, arg.Archived, arg.ID)
	return err
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE categories SET name = ?, icon = ?, color = ?, archived = ? WHERE id = ?
`

type UpdateCategoryParams struct {
	Name     string
	Icon     string
	Color    string
	Archived bool
	ID       int64
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateCategory,
		arg.Name,
		arg.Icon,
		arg.Color,
		arg.Archived,
		arg.ID,
	)
	return err
}
