// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entry_view.sql

package store

import (
	"context"
)

const getEntryView = `-- name: GetEntryView :one
SELECT id, type, date, amount_cents, category_id, category_name, parent_category_id, parent_category_name, top_category_id, payer_id, payer_name, note, status, template_id, template_month, tags_csv, created_at, updated_at FROM entry_view WHERE id = ?
`

func (q *Queries) GetEntryView(ctx context.Context, id int64) (EntryView, error) {
	row := q.db.QueryRowContext(ctx, getEntryView, id)
	var i EntryView
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Date,
		&i.AmountCents,
		&i.CategoryID,
		&i.CategoryName,
		&i.ParentCategoryID,
		&i.ParentCategoryName,
		&i.TopCategoryID,
		&i.PayerID,
		&i.PayerName,
		&i.Note,
		&i.Status,
		&i.TemplateID,
		&i.TemplateMonth,
		&i.TagsCsv,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingEntryViews = `-- name: ListPendingEntryViews :many
SELECT id, type, date, amount_cents, category_id, category_name, parent_category_id, parent_category_name, top_category_id, payer_id, payer_name, note, status, template_id, template_month, tags_csv, created_at, updated_at FROM entry_view WHERE status = 'pending' ORDER BY date, id
`

func (q *Queries) ListPendingEntryViews(ctx context.Context) ([]EntryView, error) {
	rows, err := q.db.QueryContext(ctx, listPendingEntryViews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntryView{}
	for rows.Next() {
		var i EntryView
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Date,
			&i.AmountCents,
			&i.CategoryID,
			&i.CategoryName,
			&i.ParentCategoryID,
			&i.ParentCategoryName,
			&i.TopCategoryID,
			&i.PayerID,
			&i.PayerName,
			&i.Note,
			&i.Status,
			&i.TemplateID,
			&i.TemplateMonth,
			&i.TagsCsv,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
