// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package store

import (
	"context"
)

const confirmEntry = `-- name: ConfirmEntry :exec
UPDATE entries SET status = 'confirmed', amount_cents = ?, updated_at = ? WHERE id = ?
`

type ConfirmEntryParams struct {
	AmountCents int64
	UpdatedAt   string
	ID          int64
}

func (q *Queries) ConfirmEntry(ctx context.Context, arg ConfirmEntryParams) error {
	_, err := q.db.ExecContext(ctx, confirmEntry, arg.AmountCents, arg.UpdatedAt, arg.ID)
	return err
}

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (type, date, amount_cents, category_id, payer_id, note, status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, 'confirmed', ?7, ?7)
RETURNING id
`

type CreateEntryParams struct {
	Type        string
	Date        string
	AmountCents int64
	CategoryID  int64
	PayerID     int64
	Note        string
	Now         string
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createEntry,
		arg.Type,
		arg.Date,
		arg.AmountCents,
		arg.CategoryID,
		arg.PayerID,
		arg.Note,
		arg.Now,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteEntry = `-- name: DeleteEntry :execrows
DELETE FROM entries WHERE id = ?
`

func (q *Queries) DeleteEntry(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEntry, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getEntry = `-- name: GetEntry :one
SELECT id, type, date, amount_cents, category_id, payer_id, note, status, template_id, template_month, created_at, updated_at FROM entries WHERE id = ?
`

func (q *Queries) GetEntry(ctx context.Context, id int64) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntry, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Date,
		&i.AmountCents,
		&i.CategoryID,
		&i.PayerID,
		&i.Note,
		&i.Status,
		&i.TemplateID,
		&i.TemplateMonth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEntry = `-- name: UpdateEntry :exec
UPDATE entries
SET type         = ?,
    date         = ?,
    amount_cents = ?,
    category_id  = ?,
    payer_id     = ?,
    note         = ?,
    updated_at   = ?
WHERE id = ?
`

type UpdateEntryParams struct {
	Type        string
	Date        string
	AmountCents int64
	CategoryID  int64
	PayerID     int64
	Note        string
	UpdatedAt   string
	ID          int64
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) error {
	_, err := q.db.ExecContext(ctx, updateEntry,
		arg.Type,
		arg.Date,
		arg.AmountCents,
		arg.CategoryID,
		arg.PayerID,
		arg.Note,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
