// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: export.sql

package store

import (
	"context"
)

const listExportEntries = `-- name: ListExportEntries :many
SELECT id, type, date, amount_cents, category_id, category_name, parent_category_id, parent_category_name, top_category_id, payer_id, payer_name, note, status, template_id, template_month, tags_csv, created_at, updated_at FROM entry_view
WHERE date >= ?1
  AND date <= ?2
ORDER BY date, id
`

type ListExportEntriesParams struct {
	FromDate string
	ToDate   string
}

func (q *Queries) ListExportEntries(ctx context.Context, arg ListExportEntriesParams) ([]EntryView, error) {
	rows, err := q.db.QueryContext(ctx, listExportEntries, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntryView{}
	for rows.Next() {
		var i EntryView
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Date,
			&i.AmountCents,
			&i.CategoryID,
			&i.CategoryName,
			&i.ParentCategoryID,
			&i.ParentCategoryName,
			&i.TopCategoryID,
			&i.PayerID,
			&i.PayerName,
			&i.Note,
			&i.Status,
			&i.TemplateID,
			&i.TemplateMonth,
			&i.TagsCsv,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
