// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

type Budget struct {
	ID            int64
	CategoryID    *int64
	EffectiveFrom string
	AmountCents   *int64
	CreatedAt     string
}

type Category struct {
	ID        int64
	ParentID  *int64
	Type      string
	Name      string
	Icon      string
	Color     string
	Archived  bool
	CreatedAt string
}

type Entry struct {
	ID            int64
	Type          string
	Date          string
	AmountCents   int64
	CategoryID    int64
	PayerID       int64
	Note          string
	Status        string
	TemplateID    *int64
	TemplateMonth *string
	CreatedAt     string
	UpdatedAt     string
}

type EntryTag struct {
	EntryID int64
	TagID   int64
}

type Person struct {
	ID        int64
	Name      string
	Kind      string
	SortOrder int64
	CreatedAt string
}

type Tag struct {
	ID   int64
	Name string
}

type Template struct {
	ID          int64
	Type        string
	CategoryID  int64
	PayerID     int64
	AmountCents int64
	Variable    bool
	Note        string
	StartMonth  string
	EndMonth    *string
	Active      bool
	CreatedAt   string
	UpdatedAt   string
}

type TemplateRun struct {
	TemplateID int64
	Month      string
	CreatedAt  string
}
