// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: people.sql

package store

import (
	"context"
)

const getPerson = `-- name: GetPerson :one
SELECT id, name, kind, sort_order, created_at FROM people WHERE id = ?
`

func (q *Queries) GetPerson(ctx context.Context, id int64) (Person, error) {
	row := q.db.QueryRowContext(ctx, getPerson, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listPeople = `-- name: ListPeople :many
SELECT id, name, kind, sort_order, created_at FROM people ORDER BY sort_order, id
`

func (q *Queries) ListPeople(ctx context.Context) ([]Person, error) {
	rows, err := q.db.QueryContext(ctx, listPeople)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Person{}
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renamePerson = `-- name: RenamePerson :one
UPDATE people SET name = ? WHERE id = ? RETURNING id, name, kind, sort_order, created_at
`

type RenamePersonParams struct {
	Name string
	ID   int64
}

func (q *Queries) RenamePerson(ctx context.Context, arg RenamePersonParams) (Person, error) {
	row := q.db.QueryRowContext(ctx, renamePerson, arg.Name, arg.ID)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}
