// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package store

import (
	"context"
)

const reportAggregate = `-- name: ReportAggregate :many

SELECT CAST(substr(v.date, 1, 7) AS TEXT)                 AS month,
       v.type,
       v.category_id,
       v.top_category_id,
       CAST(v.status = 'pending' AS BOOLEAN)               AS pending,
       CAST(v.template_month IS NOT NULL AS BOOLEAN)       AS recurring,
       CAST(sum(v.amount_cents) AS INTEGER)                AS amount_cents,
       CAST(count(*) AS INTEGER)                           AS entry_count
FROM entry_view v
WHERE v.date >= ?1
  AND v.date <= ?2
  AND (?3 IS NULL OR v.payer_id = ?3)
GROUP BY 1, 2, 3, 4, 5, 6
ORDER BY 1, 2, 3, 5, 6
`

type ReportAggregateParams struct {
	FromDate string
	ToDate   string
	PayerID  interface{}
}

type ReportAggregateRow struct {
	Month         string
	Type          string
	CategoryID    int64
	TopCategoryID int64
	Pending       bool
	Recurring     bool
	AmountCents   int64
	EntryCount    int64
}

// Aggregates used by /api/reports/* and /api/insights. Every query takes an
// optional payer_id filter (NULL = everyone).
// Entry totals grouped by month, type, leaf category, status and recurring flag.
func (q *Queries) ReportAggregate(ctx context.Context, arg ReportAggregateParams) ([]ReportAggregateRow, error) {
	rows, err := q.db.QueryContext(ctx, reportAggregate, arg.FromDate, arg.ToDate, arg.PayerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportAggregateRow{}
	for rows.Next() {
		var i ReportAggregateRow
		if err := rows.Scan(
			&i.Month,
			&i.Type,
			&i.CategoryID,
			&i.TopCategoryID,
			&i.Pending,
			&i.Recurring,
			&i.AmountCents,
			&i.EntryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportCategories = `-- name: ReportCategories :many
SELECT id, parent_id, type, name, icon, color, archived, created_at FROM categories ORDER BY id
`

// All categories, archived included, so history keeps its names.
func (q *Queries) ReportCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, reportCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Type,
			&i.Name,
			&i.Icon,
			&i.Color,
			&i.Archived,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportEntryYears = `-- name: ReportEntryYears :many
SELECT DISTINCT CAST(CAST(substr(e.date, 1, 4) AS INTEGER) AS INTEGER) AS year
FROM entries e
WHERE (?1 IS NULL OR e.payer_id = ?1)
ORDER BY 1 DESC
`

func (q *Queries) ReportEntryYears(ctx context.Context, payerID interface{}) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, reportEntryYears, payerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var year int64
		if err := rows.Scan(&year); err != nil {
			return nil, err
		}
		items = append(items, year)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportNonRecurringExpenseSum = `-- name: ReportNonRecurringExpenseSum :one
SELECT CAST(coalesce(sum(e.amount_cents), 0) AS INTEGER) AS amount_cents
FROM entries e
WHERE e.type = 'expense'
  AND e.template_month IS NULL
  AND e.date >= ?1
  AND e.date <= ?2
  AND (?3 IS NULL OR e.payer_id = ?3)
`

type ReportNonRecurringExpenseSumParams struct {
	FromDate string
	ToDate   string
	PayerID  interface{}
}

func (q *Queries) ReportNonRecurringExpenseSum(ctx context.Context, arg ReportNonRecurringExpenseSumParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, reportNonRecurringExpenseSum, arg.FromDate, arg.ToDate, arg.PayerID)
	var amount_cents int64
	err := row.Scan(&amount_cents)
	return amount_cents, err
}

const reportShared = `-- name: ReportShared :many
SELECT p.id,
       p.name,
       CAST(coalesce(sum(e.amount_cents), 0) AS INTEGER)                                     AS amount_cents,
       CAST(coalesce(sum(CASE WHEN e.status = 'pending' THEN e.amount_cents END), 0) AS INTEGER) AS pending_cents
FROM people p
         LEFT JOIN entries e ON e.payer_id = p.id
    AND e.type = 'expense'
    AND NOT e.personal
    AND e.date >= ?1
    AND e.date <= ?2
WHERE p.kind = 'person'
GROUP BY p.id
ORDER BY p.sort_order, p.id
`

type ReportSharedParams struct {
	FromDate string
	ToDate   string
}

type ReportSharedRow struct {
	ID           int64
	Name         string
	AmountCents  int64
	PendingCents int64
}

// Shared expenses (not personal) per person for dates from..to, household-wide:
// Joint is left out and every person is listed, even with nothing paid.
func (q *Queries) ReportShared(ctx context.Context, arg ReportSharedParams) ([]ReportSharedRow, error) {
	rows, err := q.db.QueryContext(ctx, reportShared, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportSharedRow{}
	for rows.Next() {
		var i ReportSharedRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AmountCents,
			&i.PendingCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportTemplatesStarting = `-- name: ReportTemplatesStarting :many
SELECT t.id,
       t.type,
       t.category_id,
       t.amount_cents,
       t.variable,
       t.note,
       c.name AS category_name
FROM templates t
         JOIN categories c ON c.id = t.category_id
WHERE t.start_month = ?1
  AND (?2 IS NULL OR t.payer_id = ?2)
ORDER BY t.id
`

type ReportTemplatesStartingParams struct {
	Month   string
	PayerID interface{}
}

type ReportTemplatesStartingRow struct {
	ID           int64
	Type         string
	CategoryID   int64
	AmountCents  int64
	Variable     bool
	Note         string
	CategoryName string
}

func (q *Queries) ReportTemplatesStarting(ctx context.Context, arg ReportTemplatesStartingParams) ([]ReportTemplatesStartingRow, error) {
	rows, err := q.db.QueryContext(ctx, reportTemplatesStarting, arg.Month, arg.PayerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportTemplatesStartingRow{}
	for rows.Next() {
		var i ReportTemplatesStartingRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.CategoryID,
			&i.AmountCents,
			&i.Variable,
			&i.Note,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportTopExpenses = `-- name: ReportTopExpenses :many
SELECT id, type, date, amount_cents, category_id, category_name, parent_category_id, parent_category_name, top_category_id, payer_id, payer_name, payer_kind, personal, note, status, template_id, template_month, tags_csv, created_at, updated_at FROM entry_view v
WHERE v.type = 'expense'
  AND v.date >= ?1
  AND v.date <= ?2
  AND (?3 IS NULL OR v.payer_id = ?3)
ORDER BY v.amount_cents DESC, v.date, v.id
LIMIT ?4
`

type ReportTopExpensesParams struct {
	FromDate string
	ToDate   string
	PayerID  interface{}
	MaxRows  int64
}

func (q *Queries) ReportTopExpenses(ctx context.Context, arg ReportTopExpensesParams) ([]EntryView, error) {
	rows, err := q.db.QueryContext(ctx, reportTopExpenses,
		arg.FromDate,
		arg.ToDate,
		arg.PayerID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntryView{}
	for rows.Next() {
		var i EntryView
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Date,
			&i.AmountCents,
			&i.CategoryID,
			&i.CategoryName,
			&i.ParentCategoryID,
			&i.ParentCategoryName,
			&i.TopCategoryID,
			&i.PayerID,
			&i.PayerName,
			&i.PayerKind,
			&i.Personal,
			&i.Note,
			&i.Status,
			&i.TemplateID,
			&i.TemplateMonth,
			&i.TagsCsv,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
