// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package store

import (
	"context"
)

const addEntryTag = `-- name: AddEntryTag :exec
INSERT OR IGNORE INTO entry_tags (entry_id, tag_id) VALUES (?, ?)
`

type AddEntryTagParams struct {
	EntryID int64
	TagID   int64
}

func (q *Queries) AddEntryTag(ctx context.Context, arg AddEntryTagParams) error {
	_, err := q.db.ExecContext(ctx, addEntryTag, arg.EntryID, arg.TagID)
	return err
}

const clearEntryTags = `-- name: ClearEntryTags :exec
DELETE FROM entry_tags WHERE entry_id = ?
`

func (q *Queries) ClearEntryTags(ctx context.Context, entryID int64) error {
	_, err := q.db.ExecContext(ctx, clearEntryTags, entryID)
	return err
}

const listUsedTags = `-- name: ListUsedTags :many
SELECT t.name, count(*) AS count
FROM tags t
         JOIN entry_tags et ON et.tag_id = t.id
WHERE t.name LIKE ?1 ESCAPE '\'
GROUP BY t.id, t.name
ORDER BY count DESC, t.name
LIMIT 20
`

type ListUsedTagsRow struct {
	Name  string
	Count int64
}

// pattern is a LIKE prefix pattern escaped with '\'.
func (q *Queries) ListUsedTags(ctx context.Context, pattern string) ([]ListUsedTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsedTags, pattern)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsedTagsRow{}
	for rows.Next() {
		var i ListUsedTagsRow
		if err := rows.Scan(&i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (name) VALUES (?)
ON CONFLICT (name) DO UPDATE SET name = excluded.name
RETURNING id
`

func (q *Queries) UpsertTag(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertTag, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}
