// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates.sql

package store

import (
	"context"
)

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (type, category_id, payer_id, personal, amount_cents, variable, note, start_month, end_month, active)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateTemplateParams struct {
	Type        string
	CategoryID  int64
	PayerID     int64
	Personal    bool
	AmountCents int64
	Variable    bool
	Note        string
	StartMonth  string
	EndMonth    *string
	Active      bool
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createTemplate,
		arg.Type,
		arg.CategoryID,
		arg.PayerID,
		arg.Personal,
		arg.AmountCents,
		arg.Variable,
		arg.Note,
		arg.StartMonth,
		arg.EndMonth,
		arg.Active,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteTemplate = `-- name: DeleteTemplate :execrows
DELETE FROM templates WHERE id = ?
`

func (q *Queries) DeleteTemplate(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTemplate, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTemplate = `-- name: GetTemplate :one
SELECT id, type, category_id, payer_id, amount_cents, variable, note, start_month, end_month, active, created_at, updated_at, personal FROM templates WHERE id = ?
`

func (q *Queries) GetTemplate(ctx context.Context, id int64) (Template, error) {
	row := q.db.QueryRowContext(ctx, getTemplate, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.CategoryID,
		&i.PayerID,
		&i.AmountCents,
		&i.Variable,
		&i.Note,
		&i.StartMonth,
		&i.EndMonth,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Personal,
	)
	return i, err
}

const getTemplateCategory = `-- name: GetTemplateCategory :one
SELECT id, parent_id, type, name, icon, color, archived, created_at FROM categories WHERE id = ?
`

func (q *Queries) GetTemplateCategory(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRowContext(ctx, getTemplateCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Type,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const insertGeneratedEntry = `-- name: InsertGeneratedEntry :exec
INSERT INTO entries (type, date, amount_cents, category_id, payer_id, personal, note, status, template_id, template_month)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertGeneratedEntryParams struct {
	Type          string
	Date          string
	AmountCents   int64
	CategoryID    int64
	PayerID       int64
	Personal      bool
	Note          string
	Status        string
	TemplateID    *int64
	TemplateMonth *string
}

func (q *Queries) InsertGeneratedEntry(ctx context.Context, arg InsertGeneratedEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertGeneratedEntry,
		arg.Type,
		arg.Date,
		arg.AmountCents,
		arg.CategoryID,
		arg.PayerID,
		arg.Personal,
		arg.Note,
		arg.Status,
		arg.TemplateID,
		arg.TemplateMonth,
	)
	return err
}

const insertTemplateRun = `-- name: InsertTemplateRun :exec
INSERT INTO template_runs (template_id, month) VALUES (?, ?)
`

type InsertTemplateRunParams struct {
	TemplateID int64
	Month      string
}

func (q *Queries) InsertTemplateRun(ctx context.Context, arg InsertTemplateRunParams) error {
	_, err := q.db.ExecContext(ctx, insertTemplateRun, arg.TemplateID, arg.Month)
	return err
}

const latestTemplateEntryAmount = `-- name: LatestTemplateEntryAmount :one
SELECT amount_cents FROM entries WHERE template_id = ? ORDER BY date DESC, id DESC LIMIT 1
`

func (q *Queries) LatestTemplateEntryAmount(ctx context.Context, templateID *int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, latestTemplateEntryAmount, templateID)
	var amount_cents int64
	err := row.Scan(&amount_cents)
	return amount_cents, err
}

const listActiveTemplates = `-- name: ListActiveTemplates :many
SELECT id, type, category_id, payer_id, amount_cents, variable, note, start_month, end_month, active, created_at, updated_at, personal FROM templates WHERE active ORDER BY id
`

func (q *Queries) ListActiveTemplates(ctx context.Context) ([]Template, error) {
	rows, err := q.db.QueryContext(ctx, listActiveTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.CategoryID,
			&i.PayerID,
			&i.AmountCents,
			&i.Variable,
			&i.Note,
			&i.StartMonth,
			&i.EndMonth,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Personal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateRunMonths = `-- name: ListTemplateRunMonths :many
SELECT month FROM template_runs WHERE template_id = ?
`

func (q *Queries) ListTemplateRunMonths(ctx context.Context, templateID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTemplateRunMonths, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var month string
		if err := rows.Scan(&month); err != nil {
			return nil, err
		}
		items = append(items, month)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateViews = `-- name: ListTemplateViews :many
SELECT t.id,
       t.type,
       t.category_id,
       c.name                                                                              AS category_name,
       coalesce(pc.name, '')                                                                AS parent_category_name, -- '' when top-level
       t.payer_id,
       p.name                                                                              AS payer_name,
       t.personal,
       t.amount_cents,
       t.variable,
       t.note,
       t.start_month,
       t.end_month,
       t.active,
       cast(coalesce((SELECT max(r.month) FROM template_runs r WHERE r.template_id = t.id), '') AS TEXT) AS last_generated_month
FROM templates t
         JOIN categories c ON c.id = t.category_id
         LEFT JOIN categories pc ON pc.id = c.parent_id
         JOIN people p ON p.id = t.payer_id
ORDER BY t.active DESC, t.type, c.name COLLATE NOCASE, t.id
`

type ListTemplateViewsRow struct {
	ID                 int64
	Type               string
	CategoryID         int64
	CategoryName       string
	ParentCategoryName string
	PayerID            int64
	PayerName          string
	Personal           bool
	AmountCents        int64
	Variable           bool
	Note               string
	StartMonth         string
	EndMonth           *string
	Active             bool
	LastGeneratedMonth string
}

func (q *Queries) ListTemplateViews(ctx context.Context) ([]ListTemplateViewsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTemplateViews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTemplateViewsRow{}
	for rows.Next() {
		var i ListTemplateViewsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.CategoryID,
			&i.CategoryName,
			&i.ParentCategoryName,
			&i.PayerID,
			&i.PayerName,
			&i.Personal,
			&i.AmountCents,
			&i.Variable,
			&i.Note,
			&i.StartMonth,
			&i.EndMonth,
			&i.Active,
			&i.LastGeneratedMonth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplate = `-- name: UpdateTemplate :execrows
UPDATE templates
SET type         = ?,
    category_id  = ?,
    payer_id     = ?,
    personal     = ?,
    amount_cents = ?,
    variable     = ?,
    note         = ?,
    start_month  = ?,
    end_month    = ?,
    active       = ?,
    updated_at   = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
`

type UpdateTemplateParams struct {
	Type        string
	CategoryID  int64
	PayerID     int64
	Personal    bool
	AmountCents int64
	Variable    bool
	Note        string
	StartMonth  string
	EndMonth    *string
	Active      bool
	ID          int64
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTemplate,
		arg.Type,
		arg.CategoryID,
		arg.PayerID,
		arg.Personal,
		arg.AmountCents,
		arg.Variable,
		arg.Note,
		arg.StartMonth,
		arg.EndMonth,
		arg.Active,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
